default: true

MD001: false
MD003: 
  style: atx
MD004: 
  style: dash
MD007: 
  indent: 2
MD013: false
MD024: false
MD026: 
  punctuation: ".,;:!"
MD029: 
  style: one_or_ordered
MD033: false
MD036: false
MD040: false
MD041: false