baseURL: "https://keofoxy.github.io/swift-lang-ru/"
languageCode: en-us
title: Swift Lang Ru
theme: PaperMod

params:
  # socialIcons:
  #   - name: telegram
  #     url: "https://facebook.com/"
  #   - name: x
  #     url: "https://x.com/"
  #   - name: github
  #     url: "https://github.com/"

  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true
  ShowReadingTime: true

menu:
  main:
    - identifier: Home
      name: Главная
      url: /
      weight: 10
    - identifier: Courses
      name: Курсы
      url: /courses/
      weight: 20
    - identifier: Resources
      name: Ресурсы
      url: /resources/
      weight: 20
    - identifier: Articles
      name: Статьи
      url: /articles/
      weight: 20
    - identifier: Contacts
      name: Контакты
      url: /contacts/
      weight: 30