name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.146.5'
        extended: true

    - name: Build site
      run: |
        hugo --minify --gc --config config.yml
        touch public/.nojekyll  # Важно для обработки Hugo

    - name: Verify public files
      run: ls -la public/

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        enable_jekyll: false
        user_name: "GitHub Actions"
        user_email: "41898282+github-actions[bot]@users.noreply.github.com"