name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Verify themes directory
      run: |
        ls -la themes/
        ls -la themes/PaperMod/

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
        extended: true

    - name: Build site
      run: hugo --minify --gc --config config.yml
      env:
        HUGO_ENVIRONMENT: production

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Markdown Lint
  #     uses: docker://avtodev/markdown-lint:v1
  #     with:
  #       args: "**/*.md -c .markdownlint.yml"

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # needs: [validate, lint]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
        extended: true

    - name: Build site
      run: hugo --minify --gc --config config.yml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public